### ISSUE TITLE
oidc variable requires appBaseUrl property

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-node-express-typescript-vue-example#3]
According to [Giannis Kiriakou](https://developer.okta.com/blog/2018/11/15/node-express-typescript#comment-4359340959):

> the const oidc requires the parameter `appBaseUrl:"http://localhost:8080"` to work properly!

Looking at [`sessionAuth.ts`](https://github.com/oktadeveloper/okta-node-express-typescript-vue-example/blob/master/src/middleware/sessionAuth.ts) in this repo, it doesn't have this parameter. 

Can you please investigate @reverentgeek?

**Comment by nbarbettini** [comment]
That's because of breaking changes in [oidc-middleware 2.0.0](https://github.com/okta/okta-oidc-js/releases/tag/%40okta%2Foidc-middleware%402.0.0)
> redirect_uri config option is dropped. The value is either automatically derived from the appBaseUrl and the appropriate routes option, or explicitly set as loginRedirectUri

**Comment by mraible** [comment]
The [blog post for this repo](https://developer.okta.com/blog/2018/11/15/node-express-typescript) has been updated to pin the version.

```
npm install @okta/oidc-middleware@1.0.2
```
